/**
 * Centralized API Client Wrapper
 *
 * Wraps all openapi-fetch clients and provides:
 * - Request ID extraction from response headers (set by backend RequestIdFilter)
 * - Standardized error transformation to StructuredError format
 * - Unified error handling for all API calls
 *
 * All HTTP requests receive an X-Request-Id header from the backend filter.
 * We extract this header and include it in error responses for traceability.
 *
 * NOTE: Request IDs are ALWAYS generated by the backend RequestIdFilter.
 * If a request ID is missing, that's a programming error that must be fixed.
 * We do NOT use fallback IDs to make missing IDs immediately visible.
 */

import { commandClient, queryClient, tenantClient } from './clients'
import { formatError, type FormattedError } from '@/lib/error/useErrorHandler'

/**
 * Structured error response from the API.
 * Matches the format expected by formatError().
 */
export interface StructuredError {
  errorCode: string
  message: string
  details?: Record<string, unknown>
  timestamp: string
  requestId: string
}

/**
 * Response from apiClient methods.
 * Similar to openapi-fetch, but error is pre-formatted as FormattedError.
 */
export interface ApiResponse<T> {
  data?: T
  error?: FormattedError
  response: Response
}

/**
 * Extract request ID from response headers.
 * The backend's RequestIdFilter sets this header on all responses.
 *
 * IMPORTANT: If this returns undefined, that's a programming error.
 * The backend filter should ALWAYS set the X-Request-Id header.
 * We don't use fallback IDs to make issues visible immediately.
 */
function extractRequestId(response: Response): string | undefined {
  // Check both lowercase and capitalized versions
  return response.headers.get('x-request-id') || response.headers.get('X-Request-Id') || undefined
}

/**
 * Parse error response from fetch response object.
 * Handles both JSON error responses and non-JSON responses.
 *
 * Request ID is extracted from response headers (set by backend RequestIdFilter).
 * This is guaranteed to exist on all responses if the system is working correctly.
 */
async function parseErrorFromResponse(response: Response, requestId: string | undefined): Promise<FormattedError> {
  try {
    const json = await response.json()
    // If response has errorCode, it's already structured
    if (json && typeof json === 'object' && 'errorCode' in json) {
      const structuredError: StructuredError = {
        ...json,
        // Use the extracted request ID from headers
        requestId: requestId || json.requestId || 'MISSING_REQUEST_ID',
      }
      return formatError(structuredError, response.status)
    }
    // Otherwise treat it as a generic error
    return formatError(json, response.status)
  } catch {
    // Response body is not JSON - create error from status code
    return formatError(null, response.status)
  }
}

/**
 * Wrapper for openapi-fetch requests.
 * Injects request ID and transforms errors to FormattedError.
 *
 * Usage:
 *   const { data, error } = await apiClient.command.POST('/accounts', { ... })
 *   if (error) {
 *     // error is already a FormattedError with requestId
 *     showErrorDialog(error)
 *   }
 */
class ApiClient {
  /**
   * Wrapper for command service client
   */
  readonly command = this.createClientWrapper(commandClient)

  /**
   * Wrapper for query service client
   */
  readonly query = this.createClientWrapper(queryClient)

  /**
   * Wrapper for tenant service client
   */
  readonly tenant = this.createClientWrapper(tenantClient)

  /**
   * Create a wrapper around an openapi-fetch client.
   * Intercepts responses and transforms errors.
   */
  private createClientWrapper(client: any) {
    return {
      GET: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'GET', url, options)
      },
      POST: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'POST', url, options)
      },
      PUT: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'PUT', url, options)
      },
      DELETE: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'DELETE', url, options)
      },
      PATCH: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'PATCH', url, options)
      },
      HEAD: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'HEAD', url, options)
      },
    }
  }

  /**
   * Make an HTTP request through openapi-fetch client.
   * Extracts request ID from response headers and transforms errors.
   */
  private async makeRequest<T,>(
    client: any,
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD',
    url: string,
    options?: any
  ): Promise<ApiResponse<T>> {
    try {
      // Make the request through openapi-fetch client
      const { data, error, response } = await client[method](url, options)

      // Extract request ID from response headers (set by backend RequestIdFilter)
      const requestId = extractRequestId(response)

      // If openapi-fetch returned an error, transform it
      if (error) {
        const formattedError = await parseErrorFromResponse(response, requestId)
        return {
          error: formattedError,
          response,
        }
      }

      // Success case
      return {
        data,
        response,
      }
    } catch (err) {
      // Unexpected error (e.g., network error, JSON parse error)
      const formattedError = formatError(err)

      return {
        error: formattedError,
        response: new Response(null, { status: 0 }),
      }
    }
  }
}

/**
 * Singleton instance of the centralized API client.
 * Use this for all API requests to ensure unified error handling.
 *
 * Example:
 *   const { data, error } = await apiClient.command.POST('/accounts', { ... })
 *   if (error) {
 *     console.log(`Error [${error.errorCode}]: ${error.userMessage}`)
 *     if (error.isRetryable) {
 *       // Show retry button
 *     }
 *   }
 */
export const apiClient = new ApiClient()
